# The URL the site will be built for
base_url = "https://zbrox.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

theme = "hermit-zbrox"

title = "This & That"
description = "A bit of everything, mostly about computer stuff and with all the usual caveats"

taxonomies = [
    {name = "tags"}
]

[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "https://github.com/",
]

[extra]
home_subtitle = "Rostislav's little home on the prairie hosting some words mostly about computer stuff"

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    { name = "github", link = "https://github.com/zbrox" },
    { name = "email", link = "mailto:me@zbrox.com" }
]

[extra.author]
name = "Rostislav Raykov"
email = "me@zbrox.com"

[markdown]
highlight_code = true
highlight_theme = "agola-dark"
