on:
  push:
    branches:
      - master
name: Build and deploy on push
jobs:
  build:
    name: zbrox/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.19.1
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
